version: '3.8'

services:
  service-db:
    container_name: training-diary-db
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: training_diary_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - service-db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://service-db:5432/training_diary_db
      DATABASE_USER: username
      DATABASE_PASSWORD: password

  tomcat:
    image: tomcat:jre17-temurin-jammy
    ports:
      - "8081:8080"
    depends_on:
      - myapp
volumes:
  pg_data: