version: '3.8'

services:
  service-db:
    container_name: training-diary-db
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: training_diary_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: training-diary-service
    depends_on:
      - service-db
    ports:
      - '8080:8080'
volumes:
  pg_data: