db:
  classname: org.postgresql.Driver
  url: jdbc:postgresql://service-db:5432/training_diary_db
  username: username
  password: password
  pool.size: 5
lb:
  change_log_file: db/changelog/changelog.xml
  service_schema: liquibase_service
jwt:
  secret: bc2dfaba0bf4d1ae1b36f9e03f364c6f02cee9698315d2ed866b36e6abf70e03